version: "3.9"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-microservice
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CLIENTE_SERVICE_URL=http://localhost:8085
      - SERVER_PORT=8085
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: